FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Test
WORKDIR /src/Tests
COPY ["API/API.csproj", "API/"]
COPY ["Application/Application.csproj", "Application/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]
COPY ["Tests/IntegrationTests/IntegrationTests.csproj", "Tests/IntegrationTests/"]
RUN dotnet restore "Tests/IntegrationTests/IntegrationTests.csproj"
COPY . .

ENTRYPOINT ["dotnet", "test", "--no-restore", "--logger:trx"]
